version: '3.9'
services:
  top-api.mongo:
    image: mongo
    restart: always
    container_name: top-api.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    command: --wiredTigerCacheSizeGB 1.5
    user: root
    volumes:
      - mongo_data:/data/db
  top-api.server:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env

volumes:
  mongo_data: